; aggregated from original msub.ini
; source: https://gist.githubusercontent.com/ericzhaomac/46caca8a5f226a7b7a9abbec79aba95f/raw/msub.ini
;设置规则标志位
ruleset=🎯 全球直连,[]DOMAIN-SUFFIX,local
ruleset=🎯 全球直连,https://raw.githubusercontent.com/ericzhaomac/ios_rule/main/direct.list

ruleset=🛑 广告拦截,https://raw.githubusercontent.com/ericzhaomac/ios_rule/main/advertising.list

ruleset=📲 电报消息,https://raw.githubusercontent.com/ericzhaomac/ios_rule/main/telegram.list

ruleset=🤖 AI 服务,https://raw.githubusercontent.com/ericzhaomac/ios_rule/main/ai.list

ruleset=🎬 流媒体,https://raw.githubusercontent.com/ericzhaomac/ios_rule/main/streaming.list
ruleset=🇬🇧 BBC,https://raw.githubusercontent.com/ericzhaomac/ios_rule/main/bbc.list
ruleset=🇹🇼 巴哈姆特,https://raw.githubusercontent.com/ericzhaomac/ios_rule/main/bahamut.list

ruleset=🍎 苹果服务,https://raw.githubusercontent.com/ericzhaomac/ios_rule/main/apple.list

ruleset=🐶 狗叫,https://raw.githubusercontent.com/ericzhaomac/ios_rule/main/barking.list

ruleset=🌍 全球代理,https://raw.githubusercontent.com/ericzhaomac/ios_rule/main/global.list
ruleset=🇨🇳 中国代理,https://raw.githubusercontent.com/ericzhaomac/ios_rule/main/china.list
ruleset=🇨🇳 中国代理,[]GEOIP,CN

ruleset=🐟 漏网之鱼,[]FINAL

;设置分组标志位
custom_proxy_group=🚀 节点选择`select`[]♻️ 自动选择`[]☑️ 手动切换`[]🇺🇸 JMS LA`[]🇬🇧 JMS UK`[]🇨🇳 EdNovas`[]DIRECT
custom_proxy_group=♻️ 自动选择`url-test`.*`http://www.gstatic.com/generate_204`300,,50
custom_proxy_group=☑️ 手动切换`select`.*
custom_proxy_group=📲 电报消息`select`[]🚀 节点选择`[]♻️ 自动选择`[]🇺🇸 JMS LA`[]🇬🇧 JMS UK`[]🇨🇳 EdNovas`[]DIRECT
custom_proxy_group=🤖 AI 服务`select`[]🚀 节点选择`[]♻️ 自动选择`[]🇺🇸 JMS LA`[]🇬🇧 JMS UK`[]🇨🇳 EdNovas`[]DIRECT
custom_proxy_group=🎬 流媒体`select`[]🚀 节点选择`[]♻️ 自动选择`[]🇺🇸 JMS LA`[]🇬🇧 JMS UK`[]🇨🇳 EdNovas`[]DIRECT
custom_proxy_group=🇬🇧 BBC`select`(United Kingdom|UK|英|1141894)
custom_proxy_group=🇹🇼 巴哈姆特`select`(Taiwan|TW|台)
custom_proxy_group=🍎 苹果服务`select`[]🚀 节点选择`[]♻️ 自动选择`[]DIRECT
custom_proxy_group=🐶 狗叫`select`[]🚀 节点选择`[]♻️ 自动选择`[]🇺🇸 JMS LA`[]🇬🇧 JMS UK`[]🇨🇳 EdNovas`[]DIRECT
custom_proxy_group=🌍 全球代理`select`[]🚀 节点选择`[]♻️ 自动选择`[]🇺🇸 JMS LA`[]🇬🇧 JMS UK`[]🇨🇳 EdNovas`[]DIRECT
custom_proxy_group=🇨🇳 中国代理`select`[]🚀 节点选择`[]♻️ 自动选择`[]🇺🇸 JMS LA`[]🇬🇧 JMS UK`[]🇨🇳 EdNovas`[]DIRECT
custom_proxy_group=🎯 全球直连`select`[]DIRECT`[]🚀 节点选择
custom_proxy_group=🛑 广告拦截`select`[]REJECT`[]DIRECT`[]🚀 节点选择
custom_proxy_group=🐟 漏网之鱼`select`[]🚀 节点选择`[]♻️ 自动选择`[]🇺🇸 JMS LA`[]🇬🇧 JMS UK`[]🇨🇳 EdNovas`[]DIRECT

custom_proxy_group=🇺🇸 JMS LA`select`(JMS-76241)
custom_proxy_group=🇬🇧 JMS UK`select`(JMS-1141894)
custom_proxy_group=🇨🇳 EdNovas`select`(^(?!.*JMS-).+$)

enable_rule_generator=true
overwrite_original_rules=true
